### PR TITLE
Comply with new protocol changes (Fixes #11)

### LINKED ISSUE #11: Crash at 1.16.220
07.04 19:20:14 [Server] Server thread/CRITICAL Error: "Undefined property: pocketmine\network\mcpe\protocol\InventoryTransactionPacket::$transactionType" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket" at line 195
07.04 19:20:14 [Server] Server thread/CRITICAL #0 plugins/PlayerTags_dev-21.phar/src/sys/jordan/tags/PlayerTagsListener(71): pocketmine\network\mcpe\protocol\DataPacket->__get(string[15] transactionType)
07.04 19:20:14 [Server] Server thread/CRITICAL #1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): sys\jordan\tags\PlayerTagsListener->handleDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent)
07.04 19:20:14 [Server] Server thread/CRITICAL #2 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object sys\jordan\tags\PlayerTagsListener, object pocketmine\event\server\DataPacketReceiveEvent)
07.04 19:20:14 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent)
07.04 19:20:14 [Server] Server thread/CRITICAL #4 plugins/ErrorLogger_dev-2.phar/src/vixikhd/errorlogger/network/SessionAdapter(60): pocketmine\event\Event->call()
07.04 19:20:14 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): vixikhd\errorlogger\network\SessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
07.04 19:20:14 [Server] Server thread/CRITICAL #6 plugins/ErrorLogger_dev-2.phar/src/vixikhd/errorlogger/network/SessionAdapter(63): pocketmine\network\mcpe\protocol\BatchPacket->handle(object vixikhd\errorlogger\network\SessionAdapter)
07.04 19:20:14 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/Player(3311): vixikhd\errorlogger\network\SessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
07.04 19:20:14 [Server] Server thread/CRITICAL #8 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
07.04 19:20:14 [Server] Server thread/CRITICAL #9 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[17] 81.0.39.220 20099, object raklib\protocol\EncapsulatedPacket, integer 0)
07.04 19:20:14 [Server] Server thread/CRITICAL #10 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
07.04 19:20:14 [Server] Server thread/CRITICAL #11 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
07.04 19:20:14 [Server] Server thread/CRITICAL #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
07.04 19:20:14 [Server] Server thread/CRITICAL #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
07.04 19:20:14 [Server] Server thread/CRITICAL #14 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1617823214.987)
07.04 19:20:14 [Server] Server thread/CRITICAL #15 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
07.04 19:20:14 [Server] Server thread/CRITICAL #16 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
07.04 19:20:14 [Server] Server thread/CRITICAL #17 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
07.04 19:20:14 [Server] Server thread/CRITICAL #18 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
07.04 19:20:14 [Server] Server thread/CRITICAL #19 pmsrc(11): require(string[117] phar:///PMMP-1.16.220-Latest-Stab)

### PR DESCRIPTION
**Pull request by TheNewHEROBRINEX**

### CODE REVIEW

**Comment by TheNewHEROBRINEX** [comment]
I suggest adding the mcpe-protocol directive to the plugin.yml to avoid future crashes

**Comment by UnEnanoMas** [comment]
BIG ty

**Comment by sylvrs** [comment]
Good stuff! Have you personally tested this version?

**Comment by TheNewHEROBRINEX** [comment]
Yes I did

**Comment by sylvrs** [comment]
Sorry for leaving this open for so long! I have already fixed the changes on the master branch! Thank you for the PR! 😄

**Pull request closed without merging**
